version: '3'

services:

  api:
    image: articles
    environment:
      - ConnectionStrings__ArticlesConnectionString=Server=mssql;User ID=sa;Password=Pass@word;Initial Catalog=Articles;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    depends_on:
      - mssql

  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=Pass@word
    ports:
      - "1433:1433"
    volumes:
       - mssql-data:/var/opt/mssql

volumes:
  mssql-data: